import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastBar, Toaster } from "react-hot-toast";
import ToasterComponent from "./components/toastBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ökkeş Enes Kaymaz",
  description: "Generated by OkkesEnesKaymaz",
};

export default function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToasterComponent/>
        {children}
      </body>
    </html>
  );
}
